---
title: "mRNA"
author: "Pascal Visser"
date: "23-4-2021"
output: html_document
---

```{r}
library(deSolve)
```


model = 

dR/dT = -rR + m

R is number of transcripts
r is rate of decay
m is number of new transcripts produced per second



parameters

```{r}
parameters <- c(m = 0, r = 0)
parameters_up <- c(m = 13, r = 0.1)
parameters_down <- c(m = 9, r = 0.1)
```

model

```{r}
# define model 
volume <- function(t,y,parms){
  with(as.list(c(parms)),{
         dR <- m - r * (y+m)
         return(list(c(dR)))
       }
       )
}
```

inital state

```{r}
#initial state
state <- c(Volume = 100)
```

timeframe

```{r}
#define time sequence you want to run the model
times <- seq(0, 100,  by = 1)
```

run 

```{r}
# run simulation using continuous approach
out  <- ode(times = times, y = state, parms = parameters, func = volume, method = "euler")
out_up <- ode(times = times, y = state, parms = parameters_up, func = volume, method = "euler")
out_down <- ode(times = times, y = state, parms = parameters_down, func = volume, method = "euler")

```

plot

```{r}
plot(out, out_up, out_down, col = c('red','green', 'blue'), lty = 1,
     xlab = 'Timepoints', ylab = 'Number of mRNA Transcripts', main = 'Amount of mRNA transcripts over time',
     ylim = c(55,145))
legend(72, 147, legend = c('Steady state', 'Increasing', 'Decreasing'), col = c('red', 'green', 'blue'), lty = 1, lwd = 2)
```

